# -*- coding: utf-8 -*-
"""streamlit_app_creator.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HIUHRoJGVojpffX5ZcQWYk4m0jJXIms0
"""

# Commented out IPython magic to ensure Python compatibility.
# %%writefile app.py
# import streamlit as st
# import pandas as pd
# import seaborn as sns
# import matplotlib.pyplot as plt
# 
# st.set_page_config(page_title="Bank Churn Dashboard", layout="wide")
# 
# df = pd.read_csv("European_Bank.csv")
# 
# st.title("European Bank Customer Churn Dashboard")
# 
# st.subheader("Churn by Geography")
# fig, ax = plt.subplots()
# sns.countplot(x='Geography', hue='Exited', data=df, ax=ax)
# st.pyplot(fig)
# 
# st.subheader("Churn by Age")
# fig, ax = plt.subplots()
# sns.histplot(data=df, x="Age", hue="Exited", bins=20, ax=ax)
# st.pyplot(fig)
# 
# st.subheader("Active Members vs Churn")
# fig, ax = plt.subplots()
# sns.countplot(x='IsActiveMember', hue='Exited', data=df, ax=ax)
# st.pyplot(fig)
#